SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `fs_constants`  (
  `ID` int(11) NOT NULL DEFAULT 0,
  `VERSION` int(11) NULL DEFAULT 0,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `ID`(`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

INSERT IGNORE INTO `fs_constants` SET `ID` = DEFAULT, `VERSION` = 1;

SET FOREIGN_KEY_CHECKS = 1;